# Generated by Django 3.2.12 on 2022-05-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_from', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
